-- Finaura Database Schema (auto-generated)
-- Generated: 2026-07-06T07:10:23.431Z
-- Source: supabase/migrations/
--
-- Run this file in the Supabase SQL Editor, or use: npm run db:generate
-- Do not edit this file directly — edit migration files and regenerate.


-- ========== 001_extensions.sql ==========

-- Extensions
create extension if not exists "uuid-ossp";
create extension if not exists "pgcrypto";



-- ========== 002_tables.sql ==========

-- Profiles (extends auth.users)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  email text not null,
  full_name text,
  avatar_url text,
  phone text,
  role text not null default 'user' check (role in ('user', 'agent', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Properties
create table if not exists public.properties (
  id uuid primary key default uuid_generate_v4(),
  title text not null,
  description text not null default '',
  price numeric not null check (price >= 0),
  property_type text not null check (property_type in ('appartement', 'villa', 'maison', 'terrain', 'local_commercial', 'bureau', 'ferme', 'riad')),
  status text not null default 'for_sale' check (status in ('for_sale', 'for_rent', 'sold', 'pending')),
  listing_status text not null default 'draft' check (listing_status in ('draft', 'published', 'archived')),
  bedrooms integer not null default 0 check (bedrooms >= 0),
  bathrooms integer not null default 0 check (bathrooms >= 0),
  area_sqft numeric not null default 0 check (area_sqft >= 0),
  address text not null,
  city text not null,
  state text not null,
  zip_code text not null,
  country text not null default 'Maroc',
  latitude numeric,
  longitude numeric,
  features text[] not null default '{}',
  images text[] not null default '{}',
  owner_id uuid not null references public.profiles(id) on delete cascade,
  is_featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Favorites
create table if not exists public.favorites (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  property_id uuid not null references public.properties(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(user_id, property_id)
);

-- Subscription plans
create table if not exists public.subscription_plans (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  slug text not null unique,
  price_monthly numeric not null default 0 check (price_monthly >= 0),
  max_listings integer,
  max_favorites integer,
  features text[] not null default '{}',
  stripe_price_id text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- User subscriptions
create table if not exists public.user_subscriptions (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  plan_id uuid not null references public.subscription_plans(id),
  status text not null default 'active' check (status in ('active', 'canceled', 'past_due', 'trialing')),
  stripe_customer_id text,
  stripe_subscription_id text,
  current_period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id)
);

-- Contact inquiries (messages to sellers)
create table if not exists public.contact_inquiries (
  id uuid primary key default uuid_generate_v4(),
  property_id uuid not null references public.properties(id) on delete cascade,
  sender_id uuid references public.profiles(id) on delete set null,
  sender_name text not null,
  sender_email text not null,
  sender_phone text,
  message text not null,
  created_at timestamptz not null default now()
);



-- ========== 003_indexes.sql ==========

create index if not exists idx_properties_owner on public.properties(owner_id);
create index if not exists idx_properties_city on public.properties(city);
create index if not exists idx_properties_status on public.properties(status);
create index if not exists idx_properties_listing_status on public.properties(listing_status);
create index if not exists idx_properties_price on public.properties(price);
create index if not exists idx_properties_created_at on public.properties(created_at desc);
create index if not exists idx_favorites_user on public.favorites(user_id);
create index if not exists idx_favorites_property on public.favorites(property_id);
create index if not exists idx_user_subscriptions_user on public.user_subscriptions(user_id);
create index if not exists idx_contact_inquiries_property on public.contact_inquiries(property_id);
create index if not exists idx_contact_inquiries_created_at on public.contact_inquiries(created_at desc);



-- ========== 004_functions_triggers.sql ==========

-- Seed subscription plans
insert into public.subscription_plans (name, slug, price_monthly, max_listings, max_favorites, features)
values
  ('Free', 'free', 0, 1, 10, array['Parcourir toutes les annonces', 'Enregistrer jusqu''à 10 favoris', 'Publier 1 annonce', 'Contacter les vendeurs', 'Recherche et filtres de base']),
  ('Pro', 'pro', 299, 5, null, array['Tout l''offre Gratuit', 'Favoris illimités', 'Jusqu''à 5 annonces', 'Support prioritaire', 'Tableau de bord analytique']),
  ('Enterprise', 'enterprise', 999, null, null, array['Tout l''offre Pro', 'Annonces illimitées', 'Gestion d''équipe', 'Accès API', 'Gestionnaire de compte dédié'])
on conflict (slug) do nothing;

-- Auto-create profile on signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Auto-assign free plan on profile creation
create or replace function public.handle_new_user_subscription()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  free_plan_id uuid;
begin
  select id into free_plan_id from public.subscription_plans where slug = 'free' limit 1;
  if free_plan_id is not null then
    insert into public.user_subscriptions (user_id, plan_id, status)
    values (new.id, free_plan_id, 'active')
    on conflict (user_id) do nothing;
  end if;
  return new;
end;
$$;

drop trigger if exists on_profile_created_subscription on public.profiles;
create trigger on_profile_created_subscription
  after insert on public.profiles
  for each row execute function public.handle_new_user_subscription();

-- Updated_at trigger
create or replace function public.update_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_updated_at on public.profiles;
create trigger profiles_updated_at before update on public.profiles
  for each row execute function public.update_updated_at();

drop trigger if exists properties_updated_at on public.properties;
create trigger properties_updated_at before update on public.properties
  for each row execute function public.update_updated_at();

drop trigger if exists subscription_plans_updated_at on public.subscription_plans;
create trigger subscription_plans_updated_at before update on public.subscription_plans
  for each row execute function public.update_updated_at();

drop trigger if exists user_subscriptions_updated_at on public.user_subscriptions;
create trigger user_subscriptions_updated_at before update on public.user_subscriptions
  for each row execute function public.update_updated_at();

-- Dashboard statistics for authenticated user
create or replace function public.get_dashboard_stats(p_user_id uuid)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  result json;
begin
  if auth.uid() is null or auth.uid() <> p_user_id then
    raise exception 'Unauthorized';
  end if;

  select json_build_object(
    'listings_count', (select count(*) from public.properties where owner_id = p_user_id),
    'published_count', (select count(*) from public.properties where owner_id = p_user_id and listing_status = 'published'),
    'favorites_count', (select count(*) from public.favorites where user_id = p_user_id),
    'messages_count', (
      select count(*)
      from public.contact_inquiries ci
      inner join public.properties p on p.id = ci.property_id
      where p.owner_id = p_user_id
    )
  ) into result;

  return result;
end;
$$;

grant execute on function public.get_dashboard_stats(uuid) to authenticated;



-- ========== 005_rls_policies.sql ==========

-- Enable RLS on all tables
alter table public.profiles enable row level security;
alter table public.properties enable row level security;
alter table public.favorites enable row level security;
alter table public.contact_inquiries enable row level security;
alter table public.subscription_plans enable row level security;
alter table public.user_subscriptions enable row level security;

-- Profiles
drop policy if exists "Public profiles are viewable by everyone" on public.profiles;
create policy "Public profiles are viewable by everyone"
  on public.profiles for select using (true);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
  on public.profiles for update using (auth.uid() = id);

-- Properties
drop policy if exists "Published properties are viewable by everyone" on public.properties;
create policy "Published properties are viewable by everyone"
  on public.properties for select
  using (listing_status = 'published' or auth.uid() = owner_id);

drop policy if exists "Users can insert own properties" on public.properties;
create policy "Users can insert own properties"
  on public.properties for insert
  with check (auth.uid() = owner_id);

drop policy if exists "Users can update own properties" on public.properties;
create policy "Users can update own properties"
  on public.properties for update
  using (auth.uid() = owner_id);

drop policy if exists "Users can delete own properties" on public.properties;
create policy "Users can delete own properties"
  on public.properties for delete
  using (auth.uid() = owner_id);

-- Favorites
drop policy if exists "Users can view own favorites" on public.favorites;
create policy "Users can view own favorites"
  on public.favorites for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own favorites" on public.favorites;
create policy "Users can insert own favorites"
  on public.favorites for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own favorites" on public.favorites;
create policy "Users can delete own favorites"
  on public.favorites for delete
  using (auth.uid() = user_id);

-- Contact inquiries
drop policy if exists "Property owners can view inquiries for their properties" on public.contact_inquiries;
create policy "Property owners can view inquiries for their properties"
  on public.contact_inquiries for select
  using (
    exists (
      select 1 from public.properties
      where properties.id = contact_inquiries.property_id
      and properties.owner_id = auth.uid()
    )
  );

drop policy if exists "Anyone can submit contact inquiries" on public.contact_inquiries;
create policy "Anyone can submit contact inquiries"
  on public.contact_inquiries for insert
  with check (true);

-- Subscription plans (read-only for clients)
drop policy if exists "Plans are viewable by everyone" on public.subscription_plans;
create policy "Plans are viewable by everyone"
  on public.subscription_plans for select using (is_active = true);

-- User subscriptions
drop policy if exists "Users can view own subscription" on public.user_subscriptions;
create policy "Users can view own subscription"
  on public.user_subscriptions for select
  using (auth.uid() = user_id);



-- ========== 006_storage.sql ==========

-- Property images storage bucket
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'property-images',
  'property-images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Storage RLS policies
drop policy if exists "Property images are publicly accessible" on storage.objects;
create policy "Property images are publicly accessible"
  on storage.objects for select
  using (bucket_id = 'property-images');

drop policy if exists "Authenticated users can upload property images" on storage.objects;
create policy "Authenticated users can upload property images"
  on storage.objects for insert
  with check (
    bucket_id = 'property-images'
    and auth.role() = 'authenticated'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "Users can update own property images" on storage.objects;
create policy "Users can update own property images"
  on storage.objects for update
  using (
    bucket_id = 'property-images'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

drop policy if exists "Users can delete own property images" on storage.objects;
create policy "Users can delete own property images"
  on storage.objects for delete
  using (
    bucket_id = 'property-images'
    and auth.uid()::text = (storage.foldername(name))[1]
  );



-- ========== 007_morocco_localization.sql ==========

-- Morocco property types and defaults
alter table public.properties drop constraint if exists properties_property_type_check;

update public.properties set property_type = case property_type
  when 'house' then 'maison'
  when 'apartment' then 'appartement'
  when 'condo' then 'appartement'
  when 'townhouse' then 'maison'
  when 'land' then 'terrain'
  else property_type
end;

alter table public.properties add constraint properties_property_type_check
  check (property_type in (
    'appartement', 'villa', 'maison', 'terrain',
    'local_commercial', 'bureau', 'ferme', 'riad'
  ));

alter table public.properties alter column country set default 'Maroc';

update public.properties set country = 'Maroc' where country = 'USA' or country is null;

-- Subscription plan prices in MAD
update public.subscription_plans set
  price_monthly = 0,
  features = array[
    'Parcourir toutes les annonces',
    'Enregistrer jusqu''à 10 favoris',
    'Publier 1 annonce',
    'Contacter les vendeurs',
    'Recherche et filtres de base'
  ]
where slug = 'free';

update public.subscription_plans set
  price_monthly = 299,
  features = array[
    'Tout l''offre Gratuit',
    'Favoris illimités',
    'Jusqu''à 5 annonces',
    'Support prioritaire',
    'Tableau de bord analytique'
  ]
where slug = 'pro';

update public.subscription_plans set
  price_monthly = 999,
  features = array[
    'Tout l''offre Pro',
    'Annonces illimitées',
    'Gestion d''équipe',
    'Accès API',
    'Gestionnaire de compte dédié'
  ]
where slug = 'enterprise';



-- ========== 008_seller_reputation.sql ==========

-- Seller profile extensions
alter table public.profiles add column if not exists bio text;
alter table public.profiles add column if not exists verified_seller boolean not null default false;
alter table public.profiles add column if not exists identity_verified boolean not null default false;
alter table public.profiles add column if not exists phone_verified boolean not null default false;
alter table public.profiles add column if not exists email_verified boolean not null default false;
alter table public.profiles add column if not exists response_rate numeric not null default 98 check (response_rate >= 0 and response_rate <= 100);
alter table public.profiles add column if not exists avg_response_time_hours numeric not null default 2 check (avg_response_time_hours >= 0);
alter table public.profiles add column if not exists listings_sold_count integer not null default 0 check (listings_sold_count >= 0);

-- Seller reviews
create table if not exists public.seller_reviews (
  id uuid primary key default uuid_generate_v4(),
  seller_id uuid not null references public.profiles(id) on delete cascade,
  reviewer_id uuid not null references public.profiles(id) on delete cascade,
  property_id uuid references public.properties(id) on delete set null,
  rating numeric not null check (rating >= 1 and rating <= 5),
  communication_rating integer not null check (communication_rating between 1 and 5),
  accuracy_rating integer not null check (accuracy_rating between 1 and 5),
  responsiveness_rating integer not null check (responsiveness_rating between 1 and 5),
  trust_rating integer not null check (trust_rating between 1 and 5),
  review_text text not null,
  helpful_count integer not null default 0 check (helpful_count >= 0),
  created_at timestamptz not null default now(),
  unique (seller_id, reviewer_id)
);

-- Helpful votes on reviews
create table if not exists public.review_helpful_votes (
  id uuid primary key default uuid_generate_v4(),
  review_id uuid not null references public.seller_reviews(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (review_id, user_id)
);

-- Favorite sellers
create table if not exists public.seller_favorites (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  seller_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, seller_id)
);

create index if not exists idx_seller_reviews_seller_id on public.seller_reviews(seller_id);
create index if not exists idx_seller_reviews_reviewer_id on public.seller_reviews(reviewer_id);
create index if not exists idx_review_helpful_votes_review_id on public.review_helpful_votes(review_id);
create index if not exists idx_seller_favorites_user_id on public.seller_favorites(user_id);
create index if not exists idx_seller_favorites_seller_id on public.seller_favorites(seller_id);

-- Keep helpful_count in sync
create or replace function public.sync_review_helpful_count()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    update public.seller_reviews
    set helpful_count = helpful_count + 1
    where id = new.review_id;
    return new;
  elsif tg_op = 'DELETE' then
    update public.seller_reviews
    set helpful_count = greatest(helpful_count - 1, 0)
    where id = old.review_id;
    return old;
  end if;
  return null;
end;
$$;

drop trigger if exists trg_review_helpful_insert on public.review_helpful_votes;
create trigger trg_review_helpful_insert
  after insert on public.review_helpful_votes
  for each row execute function public.sync_review_helpful_count();

drop trigger if exists trg_review_helpful_delete on public.review_helpful_votes;
create trigger trg_review_helpful_delete
  after delete on public.review_helpful_votes
  for each row execute function public.sync_review_helpful_count();

-- Auto verification flags from profile data
create or replace function public.sync_profile_verification_flags()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.email_verified := coalesce(new.email, '') <> '';
  new.phone_verified := coalesce(new.phone, '') <> '';
  if new.role = 'agent' then
    new.identity_verified := true;
  end if;
  if new.email_verified and new.phone_verified and new.identity_verified then
    new.verified_seller := true;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_profiles_verification on public.profiles;
create trigger trg_profiles_verification
  before insert or update on public.profiles
  for each row execute function public.sync_profile_verification_flags();

-- RLS
alter table public.seller_reviews enable row level security;
alter table public.review_helpful_votes enable row level security;
alter table public.seller_favorites enable row level security;

drop policy if exists "Seller reviews are viewable by everyone" on public.seller_reviews;
create policy "Seller reviews are viewable by everyone"
  on public.seller_reviews for select using (true);

drop policy if exists "Users can insert own seller reviews" on public.seller_reviews;
create policy "Users can insert own seller reviews"
  on public.seller_reviews for insert
  with check (
    auth.uid() = reviewer_id
    and auth.uid() <> seller_id
    and exists (
      select 1
      from public.contact_inquiries ci
      join public.properties p on p.id = ci.property_id
      where ci.sender_id = auth.uid()
        and p.owner_id = seller_id
    )
  );

drop policy if exists "Review helpful votes viewable by everyone" on public.review_helpful_votes;
create policy "Review helpful votes viewable by everyone"
  on public.review_helpful_votes for select using (true);

drop policy if exists "Users can manage own helpful votes" on public.review_helpful_votes;
create policy "Users can manage own helpful votes"
  on public.review_helpful_votes for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can view own seller favorites" on public.seller_favorites;
create policy "Users can view own seller favorites"
  on public.seller_favorites for select using (auth.uid() = user_id);

drop policy if exists "Users can insert own seller favorites" on public.seller_favorites;
create policy "Users can insert own seller favorites"
  on public.seller_favorites for insert
  with check (auth.uid() = user_id and auth.uid() <> seller_id);

drop policy if exists "Users can delete own seller favorites" on public.seller_favorites;
create policy "Users can delete own seller favorites"
  on public.seller_favorites for delete using (auth.uid() = user_id);



-- ========== 009_messaging.sql ==========

-- Real-time messaging: conversations, messages, read tracking

create table if not exists public.conversations (
  id uuid primary key default uuid_generate_v4(),
  property_id uuid not null references public.properties(id) on delete cascade,
  buyer_id uuid  null references public.profiles(id) on delete cascade,
  seller_id uuid not null references public.profiles(id) on delete cascade,
  last_message_text text,
  last_message_at timestamptz,
  created_at timestamptz not null default now(),
  unique (property_id, buyer_id)
);

create table if not exists public.conversation_reads (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  last_read_at timestamptz not null default now(),
  primary key (conversation_id, user_id)
);

create table if not exists public.messages (
  id uuid primary key default uuid_generate_v4(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  content text,
  attachment_url text,
  attachment_name text,
  attachment_type text check (attachment_type is null or attachment_type in ('image', 'file')),
  created_at timestamptz not null default now(),
  constraint messages_has_content check (
    (content is not null and length(trim(content)) > 0)
    or attachment_url is not null
  )
);

create index if not exists idx_conversations_buyer_id on public.conversations(buyer_id);
create index if not exists idx_conversations_seller_id on public.conversations(seller_id);
create index if not exists idx_conversations_last_message_at on public.conversations(last_message_at desc nulls last);
create index if not exists idx_messages_conversation_id on public.messages(conversation_id, created_at asc);
create index if not exists idx_messages_created_at on public.messages(created_at desc);

-- Keep conversation preview in sync
create or replace function public.sync_conversation_last_message()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.conversations
  set
    last_message_text = coalesce(
      nullif(trim(new.content), ''),
      case
        when new.attachment_type = 'image' then '📷 Image'
        when new.attachment_type = 'file' then '📎 ' || coalesce(new.attachment_name, 'File')
        else 'Message'
      end
    ),
    last_message_at = new.created_at
  where id = new.conversation_id;

  return new;
end;
$$;

drop trigger if exists trg_sync_conversation_last_message on public.messages;
create trigger trg_sync_conversation_last_message
  after insert on public.messages
  for each row execute function public.sync_conversation_last_message();

-- Seed conversations from authenticated contact inquiries
create or replace function public.create_conversation_from_inquiry()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_seller_id uuid;
  v_conversation_id uuid;
begin
  if new.sender_id is null then
    return new;
  end if;

  select owner_id into v_seller_id
  from public.properties
  where id = new.property_id;

  if v_seller_id is null or v_seller_id = new.sender_id then
    return new;
  end if;

  insert into public.conversations (
    property_id,
    buyer_id,
    seller_id,
    last_message_text,
    last_message_at
  )
  values (
    new.property_id,
    new.sender_id,
    v_seller_id,
    new.message,
    new.created_at
  )
  on conflict (property_id, buyer_id) do update
  set
    last_message_text = excluded.last_message_text,
    last_message_at = excluded.last_message_at
  returning id into v_conversation_id;

  if v_conversation_id is null then
    select id into v_conversation_id
    from public.conversations
    where property_id = new.property_id
      and buyer_id = new.sender_id;
  end if;

  insert into public.messages (conversation_id, sender_id, content, created_at)
  values (v_conversation_id, new.sender_id, new.message, new.created_at);

  return new;
end;
$$;

drop trigger if exists trg_contact_inquiry_to_conversation on public.contact_inquiries;
create trigger trg_contact_inquiry_to_conversation
  after insert on public.contact_inquiries
  for each row execute function public.create_conversation_from_inquiry();

-- Backfill existing inquiries
insert into public.conversations (property_id, buyer_id, seller_id, last_message_text, last_message_at, created_at)
select
  ci.property_id,
  ci.sender_id,
  p.owner_id,
  ci.message,
  ci.created_at,
  ci.created_at
from public.contact_inquiries ci
join public.properties p on p.id = ci.property_id
where ci.sender_id is not null
  and p.owner_id <> ci.sender_id
on conflict (property_id, buyer_id) do nothing;

insert into public.messages (conversation_id, sender_id, content, created_at)
select
  c.id,
  ci.sender_id,
  ci.message,
  ci.created_at
from public.contact_inquiries ci
join public.conversations c
  on c.property_id = ci.property_id
 and c.buyer_id = ci.sender_id
where ci.sender_id is not null
  and not exists (
    select 1
    from public.messages m
    where m.conversation_id = c.id
      and m.sender_id = ci.sender_id
      and m.content = ci.message
      and m.created_at = ci.created_at
  );

-- RLS
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.conversation_reads enable row level security;

drop policy if exists "Participants can view conversations" on public.conversations;
create policy "Participants can view conversations"
  on public.conversations for select
  using (auth.uid() = buyer_id or auth.uid() = seller_id);

drop policy if exists "Buyers can create conversations" on public.conversations;
create policy "Buyers can create conversations"
  on public.conversations for insert
  with check (auth.uid() = buyer_id);

drop policy if exists "Participants can view messages" on public.messages;
create policy "Participants can view messages"
  on public.messages for select
  using (
    exists (
      select 1 from public.conversations c
      where c.id = messages.conversation_id
        and (c.buyer_id = auth.uid() or c.seller_id = auth.uid())
    )
  );

drop policy if exists "Participants can send messages" on public.messages;
create policy "Participants can send messages"
  on public.messages for insert
  with check (
    auth.uid() = sender_id
    and exists (
      select 1 from public.conversations c
      where c.id = messages.conversation_id
        and (c.buyer_id = auth.uid() or c.seller_id = auth.uid())
    )
  );

drop policy if exists "Participants can view read state" on public.conversation_reads;
create policy "Participants can view read state"
  on public.conversation_reads for select
  using (
    exists (
      select 1 from public.conversations c
      where c.id = conversation_reads.conversation_id
        and (c.buyer_id = auth.uid() or c.seller_id = auth.uid())
    )
  );

drop policy if exists "Participants can upsert own read state" on public.conversation_reads;
create policy "Participants can upsert own read state"
  on public.conversation_reads for all
  using (auth.uid() = user_id)
  with check (
    auth.uid() = user_id
    and exists (
      select 1 from public.conversations c
      where c.id = conversation_reads.conversation_id
        and (c.buyer_id = auth.uid() or c.seller_id = auth.uid())
    )
  );

-- Message attachments storage
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'message-attachments',
  'message-attachments',
  true,
  10485760,
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif',
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'text/plain'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Message attachments are publicly accessible" on storage.objects;
create policy "Message attachments are publicly accessible"
  on storage.objects for select
  using (bucket_id = 'message-attachments');

drop policy if exists "Participants can upload message attachments" on storage.objects;
create policy "Participants can upload message attachments"
  on storage.objects for insert
  with check (
    bucket_id = 'message-attachments'
    and auth.role() = 'authenticated'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "Users can delete own message attachments" on storage.objects;
create policy "Users can delete own message attachments"
  on storage.objects for delete
  using (
    bucket_id = 'message-attachments'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

-- Realtime
alter table public.messages replica identity full;
alter table public.conversations replica identity full;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    alter publication supabase_realtime add table public.messages;
    alter publication supabase_realtime add table public.conversations;
    alter publication supabase_realtime add table public.conversation_reads;
  end if;
exception
  when duplicate_object then null;
end $$;



-- ========== 010_seller_profiles_cache.sql ==========

-- Seller profile stats cache (1:1 with profiles)
create table if not exists public.seller_profiles (
  id uuid primary key references public.profiles(id) on delete cascade,
  average_rating numeric(3, 2) not null default 0
    check (average_rating >= 0 and average_rating <= 5),
  total_reviews integer not null default 0 check (total_reviews >= 0),
  updated_at timestamptz not null default now()
);

create index if not exists idx_seller_profiles_average_rating
  on public.seller_profiles(average_rating desc);

create index if not exists idx_seller_profiles_total_reviews
  on public.seller_profiles(total_reviews desc);

-- Backfill stats from existing reviews
insert into public.seller_profiles (id, average_rating, total_reviews)
select
  p.id,
  coalesce(round(avg(sr.rating)::numeric, 2), 0),
  count(sr.id)::integer
from public.profiles p
left join public.seller_reviews sr on sr.seller_id = p.id
group by p.id
on conflict (id) do update set
  average_rating = excluded.average_rating,
  total_reviews = excluded.total_reviews,
  updated_at = now();

-- Ensure every profile has a seller_profiles row
create or replace function public.ensure_seller_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.seller_profiles (id)
  values (new.id)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists trg_ensure_seller_profile on public.profiles;
create trigger trg_ensure_seller_profile
  after insert on public.profiles
  for each row execute function public.ensure_seller_profile();

-- Recalculate average rating and review count when reviews change
create or replace function public.sync_seller_review_stats()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_seller uuid;
begin
  if tg_op = 'DELETE' then
    target_seller := old.seller_id;
  else
    target_seller := new.seller_id;
  end if;

  insert into public.seller_profiles (id, average_rating, total_reviews, updated_at)
  select
    target_seller,
    coalesce(round(avg(rating)::numeric, 2), 0),
    count(*)::integer,
    now()
  from public.seller_reviews
  where seller_id = target_seller
  on conflict (id) do update set
    average_rating = excluded.average_rating,
    total_reviews = excluded.total_reviews,
    updated_at = now();

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_seller_review_stats_insert on public.seller_reviews;
create trigger trg_seller_review_stats_insert
  after insert on public.seller_reviews
  for each row execute function public.sync_seller_review_stats();

drop trigger if exists trg_seller_review_stats_update on public.seller_reviews;
create trigger trg_seller_review_stats_update
  after update of rating on public.seller_reviews
  for each row execute function public.sync_seller_review_stats();

drop trigger if exists trg_seller_review_stats_delete on public.seller_reviews;
create trigger trg_seller_review_stats_delete
  after delete on public.seller_reviews
  for each row execute function public.sync_seller_review_stats();

alter table public.seller_profiles enable row level security;

drop policy if exists "Seller profile stats are viewable by everyone" on public.seller_profiles;
create policy "Seller profile stats are viewable by everyone"
  on public.seller_profiles for select using (true);

-- Profile avatars storage bucket
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'profile-avatars',
  'profile-avatars',
  true,
  2097152,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Profile avatars are publicly accessible" on storage.objects;
create policy "Profile avatars are publicly accessible"
  on storage.objects for select
  using (bucket_id = 'profile-avatars');

drop policy if exists "Users can upload own profile avatar" on storage.objects;
create policy "Users can upload own profile avatar"
  on storage.objects for insert
  with check (
    bucket_id = 'profile-avatars'
    and auth.role() = 'authenticated'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "Users can update own profile avatar" on storage.objects;
create policy "Users can update own profile avatar"
  on storage.objects for update
  using (
    bucket_id = 'profile-avatars'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

drop policy if exists "Users can delete own profile avatar" on storage.objects;
create policy "Users can delete own profile avatar"
  on storage.objects for delete
  using (
    bucket_id = 'profile-avatars'
    and auth.uid()::text = (storage.foldername(name))[1]
  );



-- ========== 011_verification_requests.sql ==========

-- Seller identity verification flag (document-based approval)
alter table public.profiles add column if not exists is_verified boolean not null default false;

do $$ begin
  create type public.verification_request_status as enum (
    'pending',
    'approved',
    'rejected'
  );
exception
  when duplicate_object then null;
end $$;

create table if not exists public.verification_requests (
  id uuid primary key default uuid_generate_v4(),
  seller_id uuid not null references public.profiles(id) on delete cascade,
  status public.verification_request_status not null default 'pending',
  rejection_reason text,
  id_front text not null,
  id_back text not null,
  selfie text not null,
  proof_of_address text,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references public.profiles(id) on delete set null
);

create index if not exists idx_verification_requests_seller_id
  on public.verification_requests(seller_id);

create index if not exists idx_verification_requests_status
  on public.verification_requests(status);

create index if not exists idx_verification_requests_seller_created
  on public.verification_requests(seller_id, created_at desc);

-- One pending request per seller
create unique index if not exists idx_verification_requests_one_pending
  on public.verification_requests(seller_id)
  where status = 'pending';

-- Approve seller when request is approved
create or replace function public.handle_verification_request_review()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status = 'approved' and old.status is distinct from 'approved' then
    new.reviewed_at := coalesce(new.reviewed_at, now());

    update public.profiles
    set
      is_verified = true,
      verified_seller = true,
      identity_verified = true
    where id = new.seller_id;
  elsif new.status = 'rejected' and old.status is distinct from 'rejected' then
    new.reviewed_at := coalesce(new.reviewed_at, now());
  end if;

  return new;
end;
$$;

drop trigger if exists trg_verification_request_review on public.verification_requests;
create trigger trg_verification_request_review
  before update of status on public.verification_requests
  for each row execute function public.handle_verification_request_review();

alter table public.verification_requests enable row level security;

drop policy if exists "Sellers can view own verification requests" on public.verification_requests;
create policy "Sellers can view own verification requests"
  on public.verification_requests for select
  using (
    auth.uid() = seller_id
    or exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'admin'
    )
  );

drop policy if exists "Sellers can submit verification requests" on public.verification_requests;
create policy "Sellers can submit verification requests"
  on public.verification_requests for insert
  with check (
    auth.uid() = seller_id
    and status = 'pending'
    and not exists (
      select 1 from public.verification_requests vr
      where vr.seller_id = auth.uid() and vr.status = 'pending'
    )
    and not exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.is_verified = true
    )
  );

drop policy if exists "Admins can update verification requests" on public.verification_requests;
create policy "Admins can update verification requests"
  on public.verification_requests for update
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'admin'
    )
  )
  with check (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'admin'
    )
  );

-- Private storage for verification documents
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'verification-documents',
  'verification-documents',
  false,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'application/pdf']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Sellers can upload own verification documents" on storage.objects;
create policy "Sellers can upload own verification documents"
  on storage.objects for insert
  with check (
    bucket_id = 'verification-documents'
    and auth.role() = 'authenticated'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "Sellers can read own verification documents" on storage.objects;
create policy "Sellers can read own verification documents"
  on storage.objects for select
  using (
    bucket_id = 'verification-documents'
    and (
      (storage.foldername(name))[1] = auth.uid()::text
      or exists (
        select 1 from public.profiles
        where id = auth.uid() and role = 'admin'
      )
    )
  );

drop policy if exists "Admins can manage verification documents" on storage.objects;
create policy "Admins can manage verification documents"
  on storage.objects for all
  using (
    bucket_id = 'verification-documents'
    and exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'admin'
    )
  )
  with check (
    bucket_id = 'verification-documents'
    and exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'admin'
    )
  );



-- ========== 012_admin_rls_read.sql ==========

-- Admin read access for platform statistics (role already exists on profiles)

drop policy if exists "Admins can read all properties" on public.properties;
create policy "Admins can read all properties"
  on public.properties for select
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'admin'
    )
  );

drop policy if exists "Admins can read all subscriptions" on public.user_subscriptions;
create policy "Admins can read all subscriptions"
  on public.user_subscriptions for select
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'admin'
    )
  );

drop policy if exists "Admins can read all messages" on public.messages;
create policy "Admins can read all messages"
  on public.messages for select
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'admin'
    )
  );

drop policy if exists "Admins can read all conversations" on public.conversations;
create policy "Admins can read all conversations"
  on public.conversations for select
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'admin'
    )
  );


