#!/usr/bin/env node
/**
 * Concatenates supabase/migrations/*.sql into supabase/schema.sql
 * Run: npm run db:generate
 */
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const migrationsDir = join(root, "supabase", "migrations");
const outputPath = join(root, "supabase", "schema.sql");

const files = (await readdir(migrationsDir))
  .filter((f) => f.endsWith(".sql"))
  .sort();

const header = `-- Finaura Database Schema (auto-generated)
-- Generated: ${new Date().toISOString()}
-- Source: supabase/migrations/
--
-- Run this file in the Supabase SQL Editor, or use: npm run db:generate
-- Do not edit this file directly — edit migration files and regenerate.

`;

const parts = [header];

for (const file of files) {
  const content = await readFile(join(migrationsDir, file), "utf8");
  parts.push(`-- ========== ${file} ==========\n`);
  parts.push(content.trim());
  parts.push("\n\n");
}

await writeFile(outputPath, parts.join("\n"), "utf8");
console.log(`Generated ${outputPath} from ${files.length} migration(s).`);
